<?xml version="1.0" encoding="UTF-8"?><testrun name="CustomSentimentPipelineTest" project="sentiment" tests="8" started="8" failures="1" errors="0" ignored="0">
  <testsuite name="com.asynchrony.nlp.sentiment.CustomSentimentPipelineTest" time="4.313">
    <testcase name="evaluateSentiment_Neutral" classname="com.asynchrony.nlp.sentiment.CustomSentimentPipelineTest" time="2.958"/>
    <testcase name="testSentencesWithNoAssert" classname="com.asynchrony.nlp.sentiment.CustomSentimentPipelineTest" time="0.385"/>
    <testcase name="evaluateSentiment_Very_Positive" classname="com.asynchrony.nlp.sentiment.CustomSentimentPipelineTest" time="0.027"/>
    <testcase name="evaluateSentiment_Very_Negative" classname="com.asynchrony.nlp.sentiment.CustomSentimentPipelineTest" time="0.078"/>
    <testcase name="evaluateSentiment_Positive" classname="com.asynchrony.nlp.sentiment.CustomSentimentPipelineTest" time="0.221"/>
    <testcase name="evaluateSentiment_Negative" classname="com.asynchrony.nlp.sentiment.CustomSentimentPipelineTest" time="0.455"/>
    <testcase name="evaluateSentiment_Wrongfully_Neutral" classname="com.asynchrony.nlp.sentiment.CustomSentimentPipelineTest" time="0.05">
      <failure>
        <expected>Neutral</expected>
        <actual>Negative</actual>org.junit.ComparisonFailure: Test Case [1] = Arun is great. expected:&lt;Ne[utral]&gt; but was:&lt;Ne[gative]&gt;
	at org.junit.Assert.assertEquals(Assert.java:115)
	at com.asynchrony.nlp.sentiment.CustomSentimentPipelineTest.testParticularSentiment(CustomSentimentPipelineTest.java:108)
	at com.asynchrony.nlp.sentiment.CustomSentimentPipelineTest.evaluateSentiment_Wrongfully_Neutral(CustomSentimentPipelineTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</failure>
    </testcase>
    <testcase name="evaluateSentiment_Wrongfully_Negative" classname="com.asynchrony.nlp.sentiment.CustomSentimentPipelineTest" time="0.138"/>
  </testsuite>
</testrun>
